global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'echo-app'
  scheme: https
  static_configs:
  - targets: [ "a37eadc164ab.ngrok-free.app" ] # public url for apps

- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
