name: read-replicas-mongo
services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    hostname: mongo1
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:latest
    container_name: mongo2
    hostname: mongo2
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    ports:
      - "127.0.0.2:27017:27017"
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:latest
    container_name: mongo3
    hostname: mongo3
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    ports:
      - "127.0.0.3:27017:27017"
    volumes:
      - mongo3_data:/data/db

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
